title: spooncat.dev
description: cybersecurity journey · learning in public
baseurl: ""
url: "https://spooncat.dev"
author: spooncat

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collection settings
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "spooncat"
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/ 